# fly.toml app configuration file generated for admin-dashboard-pocketbase on 2023-09-21T09:08:32+12:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "admin-dashboard-pocketbase"
primary_region = "syd"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[mounts]
  destination = "/pb_data"
  source = "pb_data"
